/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mytaskk;

/**
 *
 * @author Axellon
 * 
 */
import java.awt.HeadlessException;
import java.sql.*;
import javax.swing.*;
import java.io.*;
import javax.swing.table.DefaultTableModel;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.Timer;
import java.text.SimpleDateFormat;
import java.util.Locale;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperExportManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.view.JasperViewer;

public class halamanadmin extends javax.swing.JFrame {
    public Statement st;
    public ResultSet rs;
    private PreparedStatement ps;
     public String respon="";
     public String Status="";
     public DefaultTableModel tabmodel;
     public DefaultTableModel Tabmodel;
     public boolean databaru;
     Connection Cn = mytaskk.koneksi.getKoneksi();
     
       
     
    public void status(){
        dipakai.setActionCommand("Dipakai");
        dikembali.setActionCommand("dikembali");
    }
     public void respon(){
        cfun.setActionCommand("Fun");
        cnuf.setActionCommand("Nuf");
    }
    public halamanadmin() {
        initComponents();
        judul();
        tampilData();
        combo();
        setJam();
        judul1();
        tampilbuku();
        bdelete.setEnabled(false);
        bedit.setEnabled(false);
        tx6.setEnabled(false);
        tx44.setEnabled(false);
   
        tx4.setVisible(false);
       
        
      
       
    }
     private void combo(){
    try{
    String sql = "select * from tb_judul";
    ps = Cn.prepareStatement(sql);
    rs = ps.executeQuery();
    
    while (rs.next()){
        String nama = rs.getString("judul");
        ju.addItem(nama);
    }
    }catch(Exception e){
        JOptionPane.showMessageDialog(null, e);
    }
}
     public void tampilData(){
        try{
          st = Cn.createStatement();
         Tabmodel.getDataVector().removeAllElements();
          Tabmodel.fireTableDataChanged();
          rs = st.executeQuery("Select * from tb_input_view");
          while (rs.next()){
          Object[] data ={
              rs.getString("nama"),
              rs.getString("kelas"),
              rs.getString("namabuku"),
              rs.getString("durasi"),
              rs.getString("durasi1"),
              rs.getString("komen"),
              rs.getString("respon")
          };
          Tabmodel.addRow(data);
          }
        }catch(Exception e){
        e.printStackTrace();}
    }
    public void clear(){
     tx1.setText("");
     tx2.setText("");
     ju.setSelectedItem("");
     tx4.setText("");
     tx44.setText("");
     tx5.setText("");
     tx6.setText("");
 
    }
    public final void setJam(){
ActionListener taskPerformer = new ActionListener() {

            @Override
public void actionPerformed(ActionEvent evt) {
String nol_jam = "", nol_menit = "",nol_detik = "";

java.util.Date dateTime = new java.util.Date();
int nilai_jam = dateTime.getHours();
int nilai_menit = dateTime.getMinutes();
int nilai_detik = dateTime.getSeconds();

if(nilai_jam <= 9) nol_jam= "0";
if(nilai_menit <= 9) nol_menit= "0";
if(nilai_detik <= 9) nol_detik= "0";

String jam = nol_jam + Integer.toString(nilai_jam);
String menit = nol_menit + Integer.toString(nilai_menit);
String detik = nol_detik + Integer.toString(nilai_detik);

jLabel15.setText(jam+":"+menit+":"+detik+"");
tx4.setText(jam+":"+menit+":"+detik+"");
}
};
new Timer(1000, taskPerformer).start();
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        nm_cari = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        tx1 = new javax.swing.JTextField();
        tx2 = new javax.swing.JTextField();
        tx6 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        cnuf = new javax.swing.JRadioButton();
        tx4 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        jScrollPane2 = new javax.swing.JScrollPane();
        tx5 = new javax.swing.JTextArea();
        tx44 = new javax.swing.JTextField();
        cfun = new javax.swing.JRadioButton();
        dikembali = new javax.swing.JCheckBox();
        dipakai = new javax.swing.JCheckBox();
        jLabel6 = new javax.swing.JLabel();
        ju = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tdata = new javax.swing.JTable();
        bsimpan = new javax.swing.JButton();
        bdelete = new javax.swing.JButton();
        bedit = new javax.swing.JButton();
        bprint = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        bclear1 = new javax.swing.JButton();
        Userh = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        Userh1 = new javax.swing.JButton();
        hilangbuku = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 204, 51));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Cari");

        nm_cari.setBackground(new java.awt.Color(153, 153, 153));
        nm_cari.setFont(new java.awt.Font("Tw Cen MT Condensed", 2, 11)); // NOI18N
        nm_cari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                nm_cariKeyReleased(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("Literature Club F");

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8_Home_30px_1.png"))); // NOI18N
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addGap(18, 18, 18)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 440, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(nm_cari, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel9))
                    .addComponent(nm_cari)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(0, 13, Short.MAX_VALUE)
                                .addComponent(jLabel1))
                            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 945, -1));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        tx1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tx1ActionPerformed(evt);
            }
        });
        tx1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tx1KeyTyped(evt);
            }
        });

        tx2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tx2KeyTyped(evt);
            }
        });

        tx6.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        tx6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tx6ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jLabel2.setText("Daya Tarik");

        cnuf.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        cnuf.setText("Nuf");
        cnuf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cnufActionPerformed(evt);
            }
        });

        tx4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tx4KeyTyped(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jLabel3.setText("Nis");

        jLabel4.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jLabel4.setText("Kelas");

        jLabel5.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        jLabel5.setText("Judul");

        jLabel7.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jLabel7.setText("Penjelasan");

        tx5.setColumns(20);
        tx5.setRows(5);
        jScrollPane2.setViewportView(tx5);

        tx44.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tx44KeyTyped(evt);
            }
        });

        cfun.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        cfun.setText("Fun");
        cfun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cfunActionPerformed(evt);
            }
        });

        dikembali.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        dikembali.setText("Dikembali");
        dikembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dikembaliActionPerformed(evt);
            }
        });

        dipakai.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        dipakai.setText("Dipakai");
        dipakai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dipakaiActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        jLabel6.setText("Status");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(33, 33, 33)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(dipakai, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(6, 6, 6)))
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(dikembali, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(35, 35, 35)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 184, Short.MAX_VALUE)
                                    .addComponent(tx4, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(tx44)
                                    .addComponent(ju, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(tx2)
                                    .addComponent(jSeparator5)))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(tx1, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(cfun)
                        .addGap(18, 18, 18)
                        .addComponent(cnuf, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(80, 80, 80)
                        .addComponent(tx6)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tx1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tx2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ju, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(26, 26, 26)
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tx44, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dipakai)
                    .addComponent(dikembali))
                .addGap(38, 38, 38)
                .addComponent(tx4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cnuf)
                    .addComponent(cfun)
                    .addComponent(tx6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(786, 786, 786))
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 426, -1));

        jPanel2.setBackground(new java.awt.Color(204, 255, 0));

        tdata.setBackground(new java.awt.Color(204, 204, 255));
        tdata.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Title1", "Ttile 2", "Title 3", "Title 4", "Title 5", "Title 6", "Title 7"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tdata.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tdataMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                tdataMouseEntered(evt);
            }
        });
        jScrollPane1.setViewportView(tdata);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 444, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(57, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 60, -1, -1));

        bsimpan.setBackground(new java.awt.Color(0, 255, 204));
        bsimpan.setFont(new java.awt.Font("Tempus Sans ITC", 3, 14)); // NOI18N
        bsimpan.setText("Simpan");
        bsimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bsimpanActionPerformed(evt);
            }
        });
        getContentPane().add(bsimpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 340, -1, -1));

        bdelete.setBackground(new java.awt.Color(0, 255, 204));
        bdelete.setFont(new java.awt.Font("Tempus Sans ITC", 3, 14)); // NOI18N
        bdelete.setText("Delete");
        bdelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bdeleteActionPerformed(evt);
            }
        });
        getContentPane().add(bdelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(539, 340, -1, -1));

        bedit.setBackground(new java.awt.Color(0, 255, 204));
        bedit.setFont(new java.awt.Font("Tempus Sans ITC", 3, 14)); // NOI18N
        bedit.setText("Edit");
        bedit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                beditActionPerformed(evt);
            }
        });
        getContentPane().add(bedit, new org.netbeans.lib.awtextra.AbsoluteConstraints(632, 340, -1, -1));

        bprint.setBackground(new java.awt.Color(0, 255, 204));
        bprint.setFont(new java.awt.Font("Tempus Sans ITC", 3, 14)); // NOI18N
        bprint.setText("Print");
        bprint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bprintActionPerformed(evt);
            }
        });
        getContentPane().add(bprint, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 340, -1, -1));
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 600, 60, 30));

        bclear1.setBackground(new java.awt.Color(0, 255, 204));
        bclear1.setFont(new java.awt.Font("Tempus Sans ITC", 3, 14)); // NOI18N
        bclear1.setText("Clear");
        bclear1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bclear1ActionPerformed(evt);
            }
        });
        getContentPane().add(bclear1, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 340, -1, -1));

        Userh.setBackground(new java.awt.Color(0, 255, 204));
        Userh.setFont(new java.awt.Font("Tempus Sans ITC", 3, 14)); // NOI18N
        Userh.setText("User");
        Userh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UserhActionPerformed(evt);
            }
        });
        getContentPane().add(Userh, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 390, 70, -1));

        jPanel4.setBackground(new java.awt.Color(0, 255, 51));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Title 1"
            }
        ));
        jScrollPane3.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(317, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 430, 470, 200));

        Userh1.setBackground(new java.awt.Color(0, 255, 204));
        Userh1.setFont(new java.awt.Font("Tempus Sans ITC", 3, 14)); // NOI18N
        Userh1.setText("Input buku");
        Userh1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Userh1ActionPerformed(evt);
            }
        });
        getContentPane().add(Userh1, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 390, 120, -1));

        hilangbuku.setBackground(new java.awt.Color(0, 255, 204));
        hilangbuku.setFont(new java.awt.Font("Tempus Sans ITC", 3, 14)); // NOI18N
        hilangbuku.setText("Hilang Buku");
        hilangbuku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hilangbukuActionPerformed(evt);
            }
        });
        getContentPane().add(hilangbuku, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 390, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

   
       
    private void nm_cariKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nm_cariKeyReleased
        // TODO add your handling code here:
        try{
            st = Cn.createStatement();
            Tabmodel.getDataVector().removeAllElements();
            Tabmodel.fireTableDataChanged();
            rs=st.executeQuery("select * from tb_input where nama like '%"+ nm_cari.getText()+"%' or kelas like'%"+
                nm_cari.getText() + "%'or namabuku like'%" + nm_cari.getText()+"%'or durasi like'%"+nm_cari.getText() +"%'or durasi1 like'%" + nm_cari.getText()+"%'or komen like'%" +
                nm_cari.getText()+ "%' or respon like'%" + nm_cari.getText() + "%'");
            while (rs.next()){
                Object[] data={
                    rs.getString("nama"),
                    rs.getString("kelas"),
                    rs.getString("namabuku"),
                    rs.getString("durasi"),
                    rs.getString("durasi1"),
                    rs.getString("komen"),
                    rs.getString("respon")};

                Tabmodel.addRow(data);

            }
        }catch(Exception e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_nm_cariKeyReleased

       
    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
        // TODO add your handling code here:
        Halaman h = new Halaman();
        h.setVisible(true);
        this.setVisible(false);

    }//GEN-LAST:event_jLabel9MouseClicked

    private void tx1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tx1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tx1ActionPerformed

    private void tx1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tx1KeyTyped
        // TODO add your handling code here:
        if(!Character.isDigit(evt.getKeyChar())){
            evt.consume();
        }
    }//GEN-LAST:event_tx1KeyTyped

    private void tx6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tx6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tx6ActionPerformed

    private void cnufActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cnufActionPerformed
        // TODO add your handling code here:
        respon="Nuf";
        cfun.setSelected(false);
        tx6.setText(respon);
    }//GEN-LAST:event_cnufActionPerformed

    private void tx4KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tx4KeyTyped
        // TODO add your handling code here:

    }//GEN-LAST:event_tx4KeyTyped

    private void tx44KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tx44KeyTyped
        // TODO add your handling code here:
        if(!Character.isDigit(evt.getKeyChar())){
            evt.consume();
        }
    }//GEN-LAST:event_tx44KeyTyped

    private void cfunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cfunActionPerformed
        // TODO add your handling code here:
        respon="Fun";
        cnuf.setSelected(false);
        tx6.setText(respon);
    }//GEN-LAST:event_cfunActionPerformed

    private void dikembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dikembaliActionPerformed
        // TODO add your handling code here:
        Status = "Dikembali";
        dipakai.setSelected(false);
        tx44.setText(Status);
    }//GEN-LAST:event_dikembaliActionPerformed

    private void dipakaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dipakaiActionPerformed
        // TODO add your handling code here:
        Status = "Dipakai";
        dikembali.setSelected(false);
        tx44.setText(Status);

    }//GEN-LAST:event_dipakaiActionPerformed

    private void tdataMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tdataMouseClicked
        // TODO add your handling code here:
        tx1.setText(Tabmodel.getValueAt(tdata.getSelectedRow(), 0) + "");
        tx2.setText(Tabmodel.getValueAt(tdata.getSelectedRow(), 1) + "");
        ju.setSelectedItem(Tabmodel.getValueAt(tdata.getSelectedRow(), 2) + "");
        tx4.setText(Tabmodel.getValueAt(tdata.getSelectedRow(), 3) + "");
        tx44.setText(Tabmodel.getValueAt(tdata.getSelectedRow(),4) + "");
        tx5.setText(Tabmodel.getValueAt(tdata.getSelectedRow(), 5) + "");
        tx6.setText(Tabmodel.getValueAt(tdata.getSelectedRow(), 6) + "");
        bsimpan.setEnabled(false);
        bdelete.setEnabled(true);
        bedit.setEnabled(true);
        bclear1.setEnabled(true);
        dipakai.setEnabled(false);
    }//GEN-LAST:event_tdataMouseClicked
  public void judul1(){
   Object [] data  = {"Buku"};
       tabmodel = new DefaultTableModel(null,data);
       jTable1.setModel(tabmodel);
   }
   public void tampilbuku(){
           try{
          st = Cn.createStatement();
         tabmodel.getDataVector().removeAllElements();
          tabmodel.fireTableDataChanged();
          rs = st.executeQuery("Select * from tb_judul");
          while (rs.next()){
          Object[] data ={
            
              rs.getString("judul")
          };
             
          tabmodel.addRow(data);
          }
        }catch(Exception e){
        e.printStackTrace();}
   }
    private void tdataMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tdataMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_tdataMouseEntered

    private void bsimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bsimpanActionPerformed
        // TODO add your handling code here:

        if(tx1.getText().equals("")||tx2.getText().equals("")||ju.getSelectedItem().equals("")||tx4.getText().equals("")||tx44.getText().equals("")||tx5.getText().equals("")||tx6.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Lengkapi data!!","Kesalahan",JOptionPane.ERROR_MESSAGE);
            return;
        }else{
            try{
                st = Cn.createStatement();
                 st.executeUpdate("insert into tb_input_view values('" + tx1.getText() + "','" + tx2.getText() + "','" + ju.getSelectedItem() + "','"+ tx4.getText() +"','" + tx44.getText() + "','" + tx5.getText() + "','" + tx6.getText() +"', '"+ 0 +"' )");

               
                st.executeUpdate("insert into tb_input values('" + tx1.getText() + "','" + tx2.getText() + "','" + ju.getSelectedItem() + "','"+ tx4.getText() +"','" + tx44.getText() + "','" + tx5.getText() + "','" + tx6.getText() +"', '"+ 0 +"' )");

               
                tampilData();

            }catch(SQLException e){

                JOptionPane.showMessageDialog(null, "Duplicate Primary!");
                e.printStackTrace();

            }
        }

    }//GEN-LAST:event_bsimpanActionPerformed

    private void bdeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bdeleteActionPerformed
        // TODO add your handling code here:
        try{
            int jawab;
            if((jawab = JOptionPane.showConfirmDialog(null,"Menghapus??","Konfirmasi", JOptionPane.YES_NO_OPTION)) == 0){
                st = Cn.createStatement();
                st.executeUpdate("delete from tb_input_view where " + "nama='" + tabmodel.getValueAt(tdata.getSelectedRow(), 0) + "'");
                tampilData();
            }
            clear();
        }catch(Exception e){
            e.printStackTrace();}
    }//GEN-LAST:event_bdeleteActionPerformed

    private void beditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_beditActionPerformed
        // TODO add your handling codhere:
        try{
            st = Cn.createStatement();
            st.executeUpdate("update tb_input_view set " + "nama='" + tx1.getText() + "'," + "kelas='" + tx2.getText()+"',"+
                "namabuku='" + ju.getSelectedItem() + "'," + "durasi='" + tx4.getText() + "'," + "durasi1='" + tx44.getText() + "'," + "komen='" + tx5.getText() + "'," + "respon='" + tx6.getText() + "' where nama='"+tabmodel.getValueAt(tdata.getSelectedRow(),0)+"';");
            st.executeUpdate("update tb_input set " + "nama='" + tx1.getText() + "'," + "kelas='" + tx2.getText()+"',"+
                "namabuku='" + ju.getSelectedItem() + "'," + "durasi='" + tx4.getText() + "'," + "durasi1='" + tx44.getText() + "'," + "komen='" + tx5.getText() + "'," + "respon='" + tx6.getText() + "' where nama='"+tabmodel.getValueAt(tdata.getSelectedRow(),0)+"';");
            
            tampilData();
            clear();

            JOptionPane.showMessageDialog(null,"Berhasil!!");
        } catch(Exception e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_beditActionPerformed

    private void bprintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bprintActionPerformed
        // TODO add your handling code here:
        
        String reportSource = null;
        String reportDest = null;
        
        try{
           reportSource = "C:\\Users\\Axellon\\Documents\\NetBeansProjects\\MyTaskk\\src\\mytaskk\\report1.jrxml";
           reportDest = "C:\\Users\\Axellon\\Documents\\NetBeansProjects\\MyTaskk\\src\\mytaskk\\report1.jasper";
           
           JasperReport jasperReport = JasperCompileManager.compileReport(reportSource);
           JasperPrint jasperPrint = JasperFillManager.fillReport(jasperReport,null,koneksi.getKoneksi());
           JasperExportManager.exportReportToHtmlFile(jasperPrint, reportDest);
           JasperViewer.viewReport(jasperPrint,false);
        }catch(JRException e){
            e.printStackTrace();
        
        }
        
    }//GEN-LAST:event_bprintActionPerformed

    private void bclear1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bclear1ActionPerformed
        // TODO add your handling code here:
        clear();
        bsimpan.setVisible(true);
    }//GEN-LAST:event_bclear1ActionPerformed

    private void tx2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tx2KeyTyped
      
                                      
        // TODO add your handling code here:
         if(!Character.isDigit(evt.getKeyChar())){
            evt.consume();
    }      
    }//GEN-LAST:event_tx2KeyTyped

    private void UserhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UserhActionPerformed
       menu m = new menu();
       m.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_UserhActionPerformed

    private void Userh1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Userh1ActionPerformed
        // TODO add your handling code here:
        inputbuku b = new inputbuku();
        b.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_Userh1ActionPerformed

    private void hilangbukuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hilangbukuActionPerformed
if(tx1.getText().equals("")||tx2.getText().equals("")||ju.getSelectedItem().equals("")||tx4.getText().equals("")||tx44.getText().equals("")||tx5.getText().equals("")||tx6.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Lengkapi data!!","Kesalahan",JOptionPane.ERROR_MESSAGE);
            return;
        }else{
            try{
                st = Cn.createStatement();
               st.executeUpdate("insert into tb_hilang values('" + tx1.getText() + "','" + tx2.getText() + "','" + ju.getSelectedItem() + "','"+ tx4.getText() +"','" + tx44.getText() + "','" + tx5.getText() + "','" + tx6.getText() +"', '"+ 0 +"' )");

              
                JOptionPane.showMessageDialog(null, "Berhasil!");
                 hilang m = new hilang();
       m.setVisible(true);
        this.setVisible(false);

            }catch(SQLException e){

                JOptionPane.showMessageDialog(null, "Duplicate Primary!");
                e.printStackTrace();

            }
        }        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_hilangbukuActionPerformed
     protected void judul(){
       Object [] data  = {"Nis","Kelas","Buku","Time","Status","Komentar","Respon"};
       Tabmodel = new DefaultTableModel(null,data);
       tdata.setModel(Tabmodel);}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(halamanadmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(halamanadmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(halamanadmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(halamanadmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new halamanadmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Userh;
    private javax.swing.JButton Userh1;
    private javax.swing.JButton bclear1;
    private javax.swing.JButton bdelete;
    private javax.swing.JButton bedit;
    private javax.swing.JButton bprint;
    private javax.swing.JButton bsimpan;
    private javax.swing.JRadioButton cfun;
    private javax.swing.JRadioButton cnuf;
    private javax.swing.JCheckBox dikembali;
    private javax.swing.JCheckBox dipakai;
    private javax.swing.JButton hilangbuku;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JTable jTable1;
    private javax.swing.JComboBox<String> ju;
    private javax.swing.JTextField nm_cari;
    private javax.swing.JTable tdata;
    private javax.swing.JTextField tx1;
    private javax.swing.JTextField tx2;
    private javax.swing.JTextField tx4;
    private javax.swing.JTextField tx44;
    private javax.swing.JTextArea tx5;
    private javax.swing.JTextField tx6;
    // End of variables declaration//GEN-END:variables
}
